//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegendaryBlog.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BlogUser
    {
        [Key]
        public int ID { get; set; }
        [StringLength(maximumLength:16,MinimumLength =6)]
        public string Username { get; set; }
        [StringLength(maximumLength:16,MinimumLength =6)]
        public string Password { get; set; }
    }
}
